// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of go-ra

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/gora/v1/gora.proto

package gorav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*InterfaceStatus     `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetInterfaces() []*InterfaceStatus {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type InterfaceStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State           string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	LastUpdate      int64                  `protobuf:"varint,5,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	TxSolicitedRa   int32                  `protobuf:"varint,6,opt,name=tx_solicited_ra,json=txSolicitedRa,proto3" json:"tx_solicited_ra,omitempty"`
	TxUnsolicitedRa int32                  `protobuf:"varint,7,opt,name=tx_unsolicited_ra,json=txUnsolicitedRa,proto3" json:"tx_unsolicited_ra,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InterfaceStatus) Reset() {
	*x = InterfaceStatus{}
	mi := &file_api_gora_v1_gora_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceStatus) ProtoMessage() {}

func (x *InterfaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_gora_v1_gora_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceStatus.ProtoReflect.Descriptor instead.
func (*InterfaceStatus) Descriptor() ([]byte, []int) {
	return file_api_gora_v1_gora_proto_rawDescGZIP(), []int{2}
}

func (x *InterfaceStatus) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InterfaceStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InterfaceStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InterfaceStatus) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

func (x *InterfaceStatus) GetTxSolicitedRa() int32 {
	if x != nil {
		return x.TxSolicitedRa
	}
	return 0
}

func (x *InterfaceStatus) GetTxUnsolicitedRa() int32 {
	if x != nil {
		return x.TxUnsolicitedRa
	}
	return 0
}

var File_api_gora_v1_gora_proto protoreflect.FileDescriptor

const file_api_gora_v1_gora_proto_rawDesc = "" +
	"\n" +
	"\x16api/gora/v1/gora.proto\x12\agora.v1\"\x12\n" +
	"\x10GetStatusRequest\"M\n" +
	"\x11GetStatusResponse\x128\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\x18.gora.v1.InterfaceStatusR\n" +
	"interfaces\"\xda\x01\n" +
	"\x0fInterfaceStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1f\n" +
	"\vlast_update\x18\x05 \x01(\x03R\n" +
	"lastUpdate\x12&\n" +
	"\x0ftx_solicited_ra\x18\x06 \x01(\x05R\rtxSolicitedRa\x12*\n" +
	"\x11tx_unsolicited_ra\x18\a \x01(\x05R\x0ftxUnsolicitedRa2Q\n" +
	"\vGoRAService\x12B\n" +
	"\tGetStatus\x12\x19.gora.v1.GetStatusRequest\x1a\x1a.gora.v1.GetStatusResponseB4Z2github.com/YutaroHayakawa/go-ra/api/gora/v1;gorav1b\x06proto3"

var (
	file_api_gora_v1_gora_proto_rawDescOnce sync.Once
	file_api_gora_v1_gora_proto_rawDescData []byte
)

func file_api_gora_v1_gora_proto_rawDescGZIP() []byte {
	file_api_gora_v1_gora_proto_rawDescOnce.Do(func() {
		file_api_gora_v1_gora_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gora_v1_gora_proto_rawDesc), len(file_api_gora_v1_gora_proto_rawDesc)))
	})
	return file_api_gora_v1_gora_proto_rawDescData
}

var file_api_gora_v1_gora_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_gora_v1_gora_proto_goTypes = []any{
	(*GetStatusRequest)(nil),  // 0: gora.v1.GetStatusRequest
	(*GetStatusResponse)(nil), // 1: gora.v1.GetStatusResponse
	(*InterfaceStatus)(nil),   // 2: gora.v1.InterfaceStatus
}
var file_api_gora_v1_gora_proto_depIdxs = []int32{
	2, // 0: gora.v1.GetStatusResponse.interfaces:type_name -> gora.v1.InterfaceStatus
	0, // 1: gora.v1.GoRAService.GetStatus:input_type -> gora.v1.GetStatusRequest
	1, // 2: gora.v1.GoRAService.GetStatus:output_type -> gora.v1.GetStatusResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_gora_v1_gora_proto_init() }
func file_api_gora_v1_gora_proto_init() {
	if File_api_gora_v1_gora_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gora_v1_gora_proto_rawDesc), len(file_api_gora_v1_gora_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gora_v1_gora_proto_goTypes,
		DependencyIndexes: file_api_gora_v1_gora_proto_depIdxs,
		MessageInfos:      file_api_gora_v1_gora_proto_msgTypes,
	}.Build()
	File_api_gora_v1_gora_proto = out.File
	file_api_gora_v1_gora_proto_goTypes = nil
	file_api_gora_v1_gora_proto_depIdxs = nil
}
